### ISSUE TITLE
ChatGPT failed to refresh auth token. Error: 403 Forbidden

### ISSUE THREAD

**Issue by oguzgu** [kxxt/chatgpt-action#26]
OpenAI added Cloudflare protections to their API. For this reason get http 403 error while sending pr to review. 
Need to add "cf_clearance" and "user_agent" to request header

**Comment by kxxt** [comment]
> OpenAI added Cloudflare protections to their API. For this reason get http 403 error while sending pr to review. Need to add "cf_clearance" and "user_agent" to request header

I don't think this will work unless you are using your own computer as a self hosted runner. The cf_clearance token you get on your personal computer won't work in GitHub actions because the IP is different.
