### ISSUE TITLE
Allow reviewing the entire code base instead of just a PR

### ISSUE THREAD

**Issue by BrainStone** [kxxt/chatgpt-action#57]
I think it would be awesome if this tool could be used to review an entire repo.  
Like looking for bugs and things to improve.

**Comment by kxxt** [comment]
I don't think the ChatGPT API could handle an entire repo unless your repo is very small.

OpenAI's API even can't handle a pull request with a large diff.

**Comment by BrainStone** [comment]
Wouldn't it be possible with the method of splitting the repo up?

I'm aware that this isn't a production ready solution. I'd just like to throw in some repos out of curiosity.

**Comment by xihajun** [comment]
@BrainStone maybe you can do that if your scripts are independent, I don't think nowadays the AI is smart enough to process the logic. If you try 100.2142/1223.111 it would make it wrongly

**Comment by kxxt** [comment]
> Wouldn't it be possible with the method of splitting the repo up?

It is possible but due to the limitation of the underlying transformer model, ChatGPT simply can't remember everything you tell it. It will forget what you have told before like this example: https://github.com/LearningOS/lab5-os8-kxxt/pull/1
